// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb3DUFHnMEDqEaBQTj5XgIFk0edY19MMI',
    appId: '1:232075991557:web:81f7102f758cd54b32da6c',
    messagingSenderId: '232075991557',
    projectId: 'chronogram-auth',
    authDomain: 'chronogram.live',
    storageBucket: 'chronogram-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpZYccwd-K4ch2HkejhRCwb1djeMUHfoc',
    appId: '1:232075991557:android:abd0715c6a8d539632da6c',
    messagingSenderId: '232075991557',
    projectId: 'chronogram-auth',
    storageBucket: 'chronogram-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASW4_tHa2j9oYn6MnvKXdP-JqA82WoFT8',
    appId: '1:232075991557:ios:ce7dd710e452b55432da6c',
    messagingSenderId: '232075991557',
    projectId: 'chronogram-auth',
    storageBucket: 'chronogram-auth.firebasestorage.app',
    iosBundleId: 'com.example.chronogram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASW4_tHa2j9oYn6MnvKXdP-JqA82WoFT8',
    appId: '1:232075991557:ios:ce7dd710e452b55432da6c',
    messagingSenderId: '232075991557',
    projectId: 'chronogram-auth',
    storageBucket: 'chronogram-auth.firebasestorage.app',
    iosBundleId: 'com.example.chronogram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb3DUFHnMEDqEaBQTj5XgIFk0edY19MMI',
    appId: '1:232075991557:web:c08df97e4e46b98b32da6c',
    messagingSenderId: '232075991557',
    projectId: 'chronogram-auth',
    authDomain: 'chronogram-auth.firebaseapp.com',
    storageBucket: 'chronogram-auth.firebasestorage.app',
  );
}
